name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./python-testing.yml

      - uses: actions/checkout@v4

      - name: Update version
        uses: brettdorrans/write-version-to-file@master
        with:
          filename: 'version.py'

      - name: Pack
        run: tar -zcvf ninoxator-${{ github.ref_name }}.tar.gz *

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ./ninoxator-${{ github.ref_name }}.tar.gz
